<?php
$allowedposttags = array(
	'address' => array(),
	'a' => array(
		'class' => array (),
		'href' => array (),
		'id' => array (),
		'title' => array (),
		'rel' => array (),
		'rev' => array (),
		'name' => array (),
		'target' => array()),
	'abbr' => array(
		'class' => array (),
		'title' => array ()),
	'acronym' => array(
		'title' => array ()),
	'b' => array(),
	'big' => array(),
	'blockquote' => array(
		'id' => array (),
		'cite' => array (),
		'class' => array(),
		'lang' => array(),
		'xml:lang' => array()),
	'br' => array (
		'class' => array ()),
	'button' => array(
		'disabled' => array (),
		'name' => array (),
		'type' => array (),
		'value' => array ()),
	'caption' => array(
		'align' => array (),
		'class' => array ()),
	'cite' => array (
		'class' => array(),
		'dir' => array(),
		'lang' => array(),
		'title' => array ()),
	'code' => array (
		'style' => array()),
	'col' => array(
		'align' => array (),
		'char' => array (),
		'charoff' => array (),
		'span' => array (),
		'dir' => array(),
		'style' => array (),
		'valign' => array (),
		'width' => array ()),
	'del' => array(
		'datetime' => array ()),
	'dd' => array(),
	'div' => array(
		'align' => array (),
		'class' => array (),
		'dir' => array (),
		'id' => array (),
		'lang' => array(),
		'style' => array (),
		'xml:lang' => array()),
	'dl' => array(),
	'dt' => array(),
	'em' => array(),
	'fieldset' => array(),
	'font' => array(
		'color' => array (),
		'face' => array (),
		'size' => array ()),
	'form' => array(
		'action' => array (),
		'accept' => array (),
		'accept-charset' => array (),
		'enctype' => array (),
		'method' => array (),
		'name' => array (),
		'target' => array ()),
	'h1' => array(
		'align' => array (),
		'class' => array (),
		'id'    => array (),
		'style' => array ()),
	'h2' => array (
		'align' => array (),
		'class' => array (),
		'id'    => array (),
		'style' => array ()),
	'h3' => array (
		'align' => array (),
		'class' => array (),
		'id'    => array (),
		'style' => array ()),
	'h4' => array (
		'align' => array (),
		'class' => array (),
		'id'    => array (),
		'style' => array ()),
	'h5' => array (
		'align' => array (),
		'class' => array (),
		'id'    => array (),
		'style' => array ()),
	'h6' => array (
		'align' => array (),
		'class' => array (),
		'id'    => array (),
		'style' => array ()),
	'hr' => array (
		'align' => array (),
		'class' => array (),
		'noshade' => array (),
		'size' => array (),
		'width' => array ()),
	'i' => array(),
	'img' => array(
		'alt' => array (),
		'align' => array (),
		'border' => array (),
		'class' => array (),
		'height' => array (),
		'hspace' => array (),
		'longdesc' => array (),
		'vspace' => array (),
		'src' => array (),
		'style' => array (),
		'title' => array (),
		'width' => array ()),
	'ins' => array(
		'datetime' => array (),
		'cite' => array ()),
	'kbd' => array(),
	'label' => array(
		'for' => array ()),
	'legend' => array(
		'align' => array ()),
	'li' => array (
		'align' => array (),
		'class' => array ()),
	'p' => array(
		'class' => array (),
		'align' => array (),
		'dir' => array(),
		'lang' => array(),
		'style' => array (),
		'xml:lang' => array()),
	'pre' => array(
		'style' => array(),
		'width' => array ()),
	'q' => array(
		'cite' => array ()),
	's' => array(),
	'span' => array (
		'class' => array (),
		'dir' => array (),
		'align' => array (),
		'lang' => array (),
		'style' => array (),
		'title' => array (),
		'xml:lang' => array()),
	'strong' => array(),

	'u' => array(),
	'ul' => array (
		'class' => array (),
		'style' => array (),
		'type' => array ()),
	'ol' => array (
		'class' => array (),
		'start' => array (),
		'style' => array (),
		'type' => array ()),
	'object' => array(
            'style' => array (),
            'height' => array (),
            'width' => array (),
            'param' => array (
                    'name' => array (),
                    'value' => array ()
            ),
            'embed' => array(
                    'style' => array(),
                    'type' => array (),
                    'id' => array (),
                    'height' => array (),
                    'width' => array (),
                    'src' => array (),
                    'allowfullscreen' => array (),
                    'allowscriptaccess' => array ()
            )
    ),
	'embed' => array(
            'style' => array (),
            'height' => array (),
            'width' => array (),
            'param' => array (
                    'name' => array (),
                    'value' => array ()
            ),
            'object' => array(
                    'style' => array(),
                    'type' => array (),
                    'id' => array (),
                    'height' => array (),
                    'width' => array (),
                    'src' => array (),
                    'allowfullscreen' => array (),
                    'allowscriptaccess' => array ()
            )
    ),
	'embed' => array(
	        'style' => array(),
	        'type' => array (),
	        'id' => array (),
	        'height' => array (),
	        'width' => array (),
	        'src' => array (),
	        'allowfullscreen' => array (),
	        'allowscriptaccess' => array ()
	),
    'param' => array (
            'name' => array (),
            'value' => array ()
    ),
	'var' => array ());

/**
 * Kses allowed HTML elements.
 *
 * @global array $allowedtags
 * @since 1.0.0
 */
$allowedtags = array(
	//'a' => array(
	//	'href' => array (),
	//	'title' => array ()),
	'a' => array(
		'class' => array (),
		'href' => array (),
		'id' => array (),
		'style' => array (),
		'title' => array (),
		'name' => array (),
		'target' => array()),
	'abbr' => array(
		'title' => array ()),
	'acronym' => array(
		'title' => array ()),
	'b' => array(),
	'blockquote' => array(
		'id' => array (),
		'cite' => array (),
		'class' => array(),
		'lang' => array(),
		'xml:lang' => array()),
	'br' => array (),
	'cite' => array (),
	'code' => array(),
	'div' => array(
		'align' => array (),
		'class' => array (),
		'dir' => array (),
		'id' => array (),
		'lang' => array(),
		'style' => array (),
		'xml:lang' => array()),
	'del' => array(
		'datetime' => array ()),
	//	'dd' => array(),
	//	'dl' => array(),
	//	'dt' => array(),
	'em' => array (), 
	//	'ins' => array('datetime' => array(), 'cite' => array()),
	'i' => array(),
	'img' => array(
		'alt' => array (),
		'align' => array (),
		'border' => array (),
		'class' => array (),
		'height' => array (),
		'hspace' => array (),
		'longdesc' => array (),
		'vspace' => array (),
		'src' => array (),
		'style' => array (),
		'title' => array (),
		'width' => array ()),
	'li' => array(),
	'ol' => array(),
	//	'p' => array(),
	'q' => array(
		'cite' => array ()),
	'strong' => array(),
	'u' => array(),
	'ul' => array(),
	'object' => array(
            'style' => array (),
            'height' => array (),
            'width' => array (),
            'param' => array (
                    'name' => array (),
                    'value' => array ()
            ),
            'embed' => array(
                    'style' => array(),
                    'type' => array (),
                    'id' => array (),
                    'height' => array (),
                    'width' => array (),
                    'src' => array (),
                    'allowfullscreen' => array (),
                    'allowscriptaccess' => array ()
            )
    ),
	'embed' => array(
            'style' => array (),
            'height' => array (),
            'width' => array (),
            'param' => array (
                    'name' => array (),
                    'value' => array ()
            ),
            'object' => array(
                    'style' => array(),
                    'type' => array (),
                    'id' => array (),
                    'height' => array (),
                    'width' => array (),
                    'src' => array (),
                    'allowfullscreen' => array (),
                    'allowscriptaccess' => array ()
            )
    ),
	'embed' => array(
	        'style' => array(),
	        'type' => array (),
	        'id' => array (),
	        'height' => array (),
	        'width' => array (),
	        'src' => array (),
	        'allowfullscreen' => array (),
	        'allowscriptaccess' => array ()
	),
    'param' => array (
            'name' => array (),
            'value' => array ()
    ),
);
?>